theme: jekyll-theme-minimal
title: HCI (A) Informatics ITS
description: Webpage for HCI course (A) in Department of Informatics, ITS
logo: logo.png
show_downloads: true
google_analytics: UA-134133087-1
